--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Ubuntu 16.4-0ubuntu0.24.04.2)
-- Dumped by pg_dump version 16.4 (Ubuntu 16.4-0ubuntu0.24.04.2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: status_enum; Type: TYPE; Schema: public; Owner: asgef
--

CREATE TYPE public.status_enum AS ENUM (
    'pending',
    'accepted',
    'declined',
    'canceled'
);


ALTER TYPE public.status_enum OWNER TO asgef;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: academic_subject; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.academic_subject (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(1000) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.academic_subject OWNER TO asgef;

--
-- Name: academic_subject_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

CREATE SEQUENCE public.academic_subject_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.academic_subject_id_seq OWNER TO asgef;

--
-- Name: academic_subject_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: asgef
--

ALTER SEQUENCE public.academic_subject_id_seq OWNED BY public.academic_subject.id;


--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


ALTER TABLE public.alembic_version OWNER TO asgef;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO asgef;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO asgef;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO asgef;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO asgef;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO asgef;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO asgef;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO asgef;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO asgef;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO asgef;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO asgef;

--
-- Name: order; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public."order" (
    id integer NOT NULL,
    student_id integer NOT NULL,
    tutor_id integer NOT NULL,
    slot_id integer NOT NULL,
    subject_id integer NOT NULL,
    status public.status_enum NOT NULL,
    comment character varying(255),
    date timestamp without time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public."order" OWNER TO asgef;

--
-- Name: order_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

CREATE SEQUENCE public.order_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.order_id_seq OWNER TO asgef;

--
-- Name: order_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: asgef
--

ALTER SEQUENCE public.order_id_seq OWNED BY public."order".id;


--
-- Name: schedule_calendar; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.schedule_calendar (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    slug character varying(200) NOT NULL
);


ALTER TABLE public.schedule_calendar OWNER TO asgef;

--
-- Name: schedule_calendar_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

ALTER TABLE public.schedule_calendar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_calendar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedule_calendarrelation; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.schedule_calendarrelation (
    id integer NOT NULL,
    object_id integer NOT NULL,
    distinction character varying(20) NOT NULL,
    inheritable boolean NOT NULL,
    calendar_id integer NOT NULL,
    content_type_id integer NOT NULL
);


ALTER TABLE public.schedule_calendarrelation OWNER TO asgef;

--
-- Name: schedule_calendarrelation_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

ALTER TABLE public.schedule_calendarrelation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_calendarrelation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedule_event; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.schedule_event (
    id integer NOT NULL,
    start timestamp with time zone NOT NULL,
    "end" timestamp with time zone NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    created_on timestamp with time zone NOT NULL,
    updated_on timestamp with time zone NOT NULL,
    end_recurring_period timestamp with time zone,
    color_event character varying(10) NOT NULL,
    calendar_id integer NOT NULL,
    creator_id integer,
    rule_id integer
);


ALTER TABLE public.schedule_event OWNER TO asgef;

--
-- Name: schedule_event_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

ALTER TABLE public.schedule_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedule_eventrelation; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.schedule_eventrelation (
    id integer NOT NULL,
    object_id integer NOT NULL,
    distinction character varying(20) NOT NULL,
    content_type_id integer NOT NULL,
    event_id integer NOT NULL
);


ALTER TABLE public.schedule_eventrelation OWNER TO asgef;

--
-- Name: schedule_eventrelation_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

ALTER TABLE public.schedule_eventrelation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_eventrelation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedule_occurrence; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.schedule_occurrence (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    start timestamp with time zone NOT NULL,
    "end" timestamp with time zone NOT NULL,
    cancelled boolean NOT NULL,
    original_start timestamp with time zone NOT NULL,
    original_end timestamp with time zone NOT NULL,
    created_on timestamp with time zone NOT NULL,
    updated_on timestamp with time zone NOT NULL,
    event_id integer NOT NULL
);


ALTER TABLE public.schedule_occurrence OWNER TO asgef;

--
-- Name: schedule_occurrence_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

ALTER TABLE public.schedule_occurrence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_occurrence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedule_rule; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.schedule_rule (
    id integer NOT NULL,
    name character varying(32) NOT NULL,
    description text NOT NULL,
    frequency character varying(10) NOT NULL,
    params text NOT NULL
);


ALTER TABLE public.schedule_rule OWNER TO asgef;

--
-- Name: schedule_rule_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

ALTER TABLE public.schedule_rule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: slot; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public.slot (
    id integer NOT NULL,
    date timestamp without time zone NOT NULL,
    time_start time without time zone NOT NULL,
    time_end time without time zone NOT NULL,
    tutor_id integer NOT NULL,
    student_id integer,
    is_available boolean NOT NULL,
    comment character varying(255)
);


ALTER TABLE public.slot OWNER TO asgef;

--
-- Name: slot_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

CREATE SEQUENCE public.slot_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.slot_id_seq OWNER TO asgef;

--
-- Name: slot_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: asgef
--

ALTER SEQUENCE public.slot_id_seq OWNED BY public.slot.id;


--
-- Name: user; Type: TABLE; Schema: public; Owner: asgef
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    tg_id bigint NOT NULL,
    username character varying(150),
    first_name character varying(150),
    last_name character varying(150),
    is_admin boolean NOT NULL,
    timezone character varying(50) NOT NULL,
    last_activity timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public."user" OWNER TO asgef;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: asgef
--

CREATE SEQUENCE public.user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_id_seq OWNER TO asgef;

--
-- Name: user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: asgef
--

ALTER SEQUENCE public.user_id_seq OWNED BY public."user".id;


--
-- Name: academic_subject id; Type: DEFAULT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.academic_subject ALTER COLUMN id SET DEFAULT nextval('public.academic_subject_id_seq'::regclass);


--
-- Name: order id; Type: DEFAULT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public."order" ALTER COLUMN id SET DEFAULT nextval('public.order_id_seq'::regclass);


--
-- Name: slot id; Type: DEFAULT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.slot ALTER COLUMN id SET DEFAULT nextval('public.slot_id_seq'::regclass);


--
-- Name: user id; Type: DEFAULT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public."user" ALTER COLUMN id SET DEFAULT nextval('public.user_id_seq'::regclass);


--
-- Name: academic_subject academic_subject_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.academic_subject
    ADD CONSTRAINT academic_subject_pkey PRIMARY KEY (id);


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: order order_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_pkey PRIMARY KEY (id);


--
-- Name: schedule_calendar schedule_calendar_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.schedule_calendar
    ADD CONSTRAINT schedule_calendar_pkey PRIMARY KEY (id);


--
-- Name: schedule_calendar schedule_calendar_slug_key; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.schedule_calendar
    ADD CONSTRAINT schedule_calendar_slug_key UNIQUE (slug);


--
-- Name: schedule_calendarrelation schedule_calendarrelation_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.schedule_calendarrelation
    ADD CONSTRAINT schedule_calendarrelation_pkey PRIMARY KEY (id);


--
-- Name: schedule_event schedule_event_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.schedule_event
    ADD CONSTRAINT schedule_event_pkey PRIMARY KEY (id);


--
-- Name: schedule_eventrelation schedule_eventrelation_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.schedule_eventrelation
    ADD CONSTRAINT schedule_eventrelation_pkey PRIMARY KEY (id);


--
-- Name: schedule_occurrence schedule_occurrence_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.schedule_occurrence
    ADD CONSTRAINT schedule_occurrence_pkey PRIMARY KEY (id);


--
-- Name: schedule_rule schedule_rule_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.schedule_rule
    ADD CONSTRAINT schedule_rule_pkey PRIMARY KEY (id);


--
-- Name: slot slot_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.slot
    ADD CONSTRAINT slot_pkey PRIMARY KEY (id);


--
-- Name: user user_first_name_key; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_first_name_key UNIQUE (first_name);


--
-- Name: user user_last_name_key; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_last_name_key UNIQUE (last_name);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: user user_tg_id_key; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_tg_id_key UNIQUE (tg_id);


--
-- Name: user user_username_key; Type: CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: schedule_ca_calenda_ea7406_idx; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_ca_calenda_ea7406_idx ON public.schedule_calendarrelation USING btree (calendar_id, object_id);


--
-- Name: schedule_calendar_slug_ba17e861_like; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_calendar_slug_ba17e861_like ON public.schedule_calendar USING btree (slug varchar_pattern_ops);


--
-- Name: schedule_calendarrelation_calendar_id_0a50be2e; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_calendarrelation_calendar_id_0a50be2e ON public.schedule_calendarrelation USING btree (calendar_id);


--
-- Name: schedule_calendarrelation_content_type_id_f2a42f5b; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_calendarrelation_content_type_id_f2a42f5b ON public.schedule_calendarrelation USING btree (content_type_id);


--
-- Name: schedule_calendarrelation_object_id_1743bce6; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_calendarrelation_object_id_1743bce6 ON public.schedule_calendarrelation USING btree (object_id);


--
-- Name: schedule_ev_content_6ceecb_idx; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_ev_content_6ceecb_idx ON public.schedule_eventrelation USING btree (content_type_id, object_id);


--
-- Name: schedule_ev_start_a258cb_idx; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_ev_start_a258cb_idx ON public.schedule_event USING btree (start, "end");


--
-- Name: schedule_event_calendar_id_eb1c700f; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_event_calendar_id_eb1c700f ON public.schedule_event USING btree (calendar_id);


--
-- Name: schedule_event_creator_id_d2ffab6e; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_event_creator_id_d2ffab6e ON public.schedule_event USING btree (creator_id);


--
-- Name: schedule_event_end_674c5848; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_event_end_674c5848 ON public.schedule_event USING btree ("end");


--
-- Name: schedule_event_end_recurring_period_672addcf; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_event_end_recurring_period_672addcf ON public.schedule_event USING btree (end_recurring_period);


--
-- Name: schedule_event_rule_id_90b83d31; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_event_rule_id_90b83d31 ON public.schedule_event USING btree (rule_id);


--
-- Name: schedule_event_start_a11492a7; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_event_start_a11492a7 ON public.schedule_event USING btree (start);


--
-- Name: schedule_eventrelation_content_type_id_d4187723; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_eventrelation_content_type_id_d4187723 ON public.schedule_eventrelation USING btree (content_type_id);


--
-- Name: schedule_eventrelation_event_id_8c57a7b4; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_eventrelation_event_id_8c57a7b4 ON public.schedule_eventrelation USING btree (event_id);


--
-- Name: schedule_eventrelation_object_id_e22334a2; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_eventrelation_object_id_e22334a2 ON public.schedule_eventrelation USING btree (object_id);


--
-- Name: schedule_oc_start_76a2f8_idx; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_oc_start_76a2f8_idx ON public.schedule_occurrence USING btree (start, "end");


--
-- Name: schedule_occurrence_end_ae255624; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_occurrence_end_ae255624 ON public.schedule_occurrence USING btree ("end");


--
-- Name: schedule_occurrence_event_id_ade47cd8; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_occurrence_event_id_ade47cd8 ON public.schedule_occurrence USING btree (event_id);


--
-- Name: schedule_occurrence_start_b28eeb2f; Type: INDEX; Schema: public; Owner: asgef
--

CREATE INDEX schedule_occurrence_start_b28eeb2f ON public.schedule_occurrence USING btree (start);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order order_slot_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_slot_id_fkey FOREIGN KEY (slot_id) REFERENCES public.slot(id);


--
-- Name: order order_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_student_id_fkey FOREIGN KEY (student_id) REFERENCES public."user"(id);


--
-- Name: order order_subject_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.academic_subject(id);


--
-- Name: order order_tutor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_tutor_id_fkey FOREIGN KEY (tutor_id) REFERENCES public."user"(id);


--
-- Name: schedule_calendarrelation schedule_calendarrel_calendar_id_0a50be2e_fk_schedule_; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.schedule_calendarrelation
    ADD CONSTRAINT schedule_calendarrel_calendar_id_0a50be2e_fk_schedule_ FOREIGN KEY (calendar_id) REFERENCES public.schedule_calendar(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schedule_calendarrelation schedule_calendarrel_content_type_id_f2a42f5b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.schedule_calendarrelation
    ADD CONSTRAINT schedule_calendarrel_content_type_id_f2a42f5b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schedule_event schedule_event_calendar_id_eb1c700f_fk_schedule_calendar_id; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.schedule_event
    ADD CONSTRAINT schedule_event_calendar_id_eb1c700f_fk_schedule_calendar_id FOREIGN KEY (calendar_id) REFERENCES public.schedule_calendar(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schedule_event schedule_event_creator_id_d2ffab6e_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.schedule_event
    ADD CONSTRAINT schedule_event_creator_id_d2ffab6e_fk_auth_user_id FOREIGN KEY (creator_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schedule_event schedule_event_rule_id_90b83d31_fk_schedule_rule_id; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.schedule_event
    ADD CONSTRAINT schedule_event_rule_id_90b83d31_fk_schedule_rule_id FOREIGN KEY (rule_id) REFERENCES public.schedule_rule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schedule_eventrelation schedule_eventrelati_content_type_id_d4187723_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.schedule_eventrelation
    ADD CONSTRAINT schedule_eventrelati_content_type_id_d4187723_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schedule_eventrelation schedule_eventrelation_event_id_8c57a7b4_fk_schedule_event_id; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.schedule_eventrelation
    ADD CONSTRAINT schedule_eventrelation_event_id_8c57a7b4_fk_schedule_event_id FOREIGN KEY (event_id) REFERENCES public.schedule_event(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schedule_occurrence schedule_occurrence_event_id_ade47cd8_fk_schedule_event_id; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.schedule_occurrence
    ADD CONSTRAINT schedule_occurrence_event_id_ade47cd8_fk_schedule_event_id FOREIGN KEY (event_id) REFERENCES public.schedule_event(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: slot slot_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.slot
    ADD CONSTRAINT slot_student_id_fkey FOREIGN KEY (student_id) REFERENCES public."user"(id);


--
-- Name: slot slot_tutor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: asgef
--

ALTER TABLE ONLY public.slot
    ADD CONSTRAINT slot_tutor_id_fkey FOREIGN KEY (tutor_id) REFERENCES public."user"(id);


--
-- PostgreSQL database dump complete
--

